default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: store_api_dev

test:
  <<: *default
  database: store_api_test

production:
  <<: *default
  database: store_api
